import { defineConfig } from '@playwright/test';
import dotenv from 'dotenv';
import path from 'path';

// Read from .env file
dotenv.config({ path: path.resolve(__dirname, '.env') });

/**
 * Playwright API Testing Configuration
 * Generated by ATG Wizard
 */
export default defineConfig({
  testDir: './tests/setup',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : 1,
  reporter: [
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
    ['list'],
    ['json', { outputFile: 'test-results/results.json' }],
    // Custom reporter: auto-generates reports/test-report.html and reports/test-report-summary.md
    ['./utils/test-reporter']
  ],
  use: {
    // Base URL from .env or wizard config
    baseURL: process.env.BASE_URL ?? 'https://dummyjson.com',

    // Collect specific traces for failed API calls
    trace: 'on-first-retry',

    // Global Headers
    extraHTTPHeaders: {
      'Accept': 'application/json',
      // We do NOT set Content-Type: application/json here to allow Playwright 
      // automatically detect and set it for multipart/form-data or url-encoded requests.
    },

    // Timeout for each individual request (from wizard Step 3)
    actionTimeout: 10000,
  },

  // Total timeout for each test (from wizard Step 3)
  timeout: 30000,

  projects: [
    { name: 'fase-1-public', testDir: './tests/01-public', fullyParallel: true }
  ],
});